# Generated by Django 3.2.13 on 2022-05-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220516_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.FloatField(default=0, null=True),
        ),
    ]
